ACTUAL BUG: Null substring calls fixed - incognito will work now
REAL BUG FROM CONSOLE:
TypeError: Cannot read properties of null (reading 'substring')

FOUND 3 LOCATIONS:
Line 712: notif.user_id.substring()
Line 717: notif.onesignal_notification_id.substring()
Line 952: user.device_token.substring()

FIX APPLIED:
Added optional chaining (?.) to all:
- notif.user_id?.substring(0, 8) || 'N/A'
- notif.onesignal_notification_id?.substring(0, 20)
- user.device_token?.substring(0, 20)

THIS WAS CAUSING COMPONENT ERROR IN INCOGNITO

DEPLOYED TO PRODUCTION:
Commit: f21a40e4
Status: LIVE

TEST: Incognito should work now

See ACTUAL_BUG_NULL_SUBSTRING.md